name: Golang CI/CD

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ github.actor }}
  IMAGE_NAME: ferferi
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod download

      - name: Build application
        run: go build -o ferferi cmd/server/main.go

      - name: Run tests
        run: go test ./...

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}